[api]
api_url="https://virtserver.swaggerhub.com/wcd_de_lab/top10/1.0.0/add"

[s3]
bucket='de-exercise-data-bucket'
folder='input'

[db]
host='cgfixubzkzib.us-east-1.rds.amazonaws.com'
port=3306
database='database'
schema='superstore'

[run]
py_script="run.py"




    

    